---
title: "Suivi des contrôles Alim Confiance"
output:
  html_document:
    df_print: paged
---


```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(scales)
library(tidyr)
library(DT)
table_count_satisfaction <- read_csv("data/table_count_satisfaction.csv")
```

* Mis à jour le `r today()`.

## Part des contrôles satisfaisants

```{r, echo=FALSE, results='markup'}
table_count_satisfaction %>% 
  group_by(Synthese_eval_sanit) %>%
  summarise(n = sum(n)) %>%
  mutate(share = 100 * n / sum(n)) %>%
  datatable()
```

## Evolution du nombre de contrôles

```{r echo=FALSE}
table_count_satisfaction %>%
  mutate(
    date = ymd(date)
    ) %>%
  group_by(date) %>%
  summarise(n = sum(n)) %>%
  ggplot() + 
  geom_point(mapping = aes(x = date, y = n)) + 
  scale_x_date() + 
  scale_y_continuous()
```

## Evolution des évaluations par mois

```{r echo=FALSE}
table_count_satisfaction %>%
  mutate(
    date = ymd(date),
    month_year = ymd(paste(year(date), month(date), "01", sep = "-"))
    ) %>%
  group_by(Synthese_eval_sanit, month_year) %>%
  summarise(n = sum(n)) %>%
  group_by(month_year) %>%
  mutate(share = 100 * n/sum(n)) %>%
  ggplot() + 
  geom_point(
    mapping = aes(x = month_year, y = share)
  ) + 
  facet_wrap(~ Synthese_eval_sanit) + 
  scale_y_continuous(name = "%") + 
  scale_x_date(name = "Date", date_breaks = "6 months")
```

### Données détaillées

```{r echo=FALSE}
table_count_satisfaction %>%
    mutate(
      date = ymd(date),
      month_year = ymd(paste(year(date), month(date), "01", sep = "-"))
    ) %>%
    group_by(Synthese_eval_sanit, month_year) %>%
    summarise(n = sum(n)) %>%
    group_by(month_year) %>%
    mutate(share = n/sum(n)) %>% 
    select(Synthese_eval_sanit, share, month_year) %>%
    spread(key = Synthese_eval_sanit, value = share) %>%
    datatable() %>%
    formatPercentage(columns = ~ `A améliorer` + `A corriger de manière urgente` + Satisfaisant + `Très satisfaisant`, 2)
```

## Pour aller plus loin

* [Code source](https://github.com/pachevalier/alimconfiance)
* [Source des données](http://data.cquest.org/alim_confiance/)
